### PR TITLE
Cleanup and templetization of oomph setup

### PR DESCRIPTION
**Pull request by maxandersen**
Two things in this:
1. Remove all unnecessary .setup files
2. Add template generation for jbosstools so we don't have to type/maintain so much oomph xml gunk

See readme.md for details.

### CODE REVIEW

**Comment by dgolovin** [comment]
I got the idea and I relly like it, but there are some problems that should be addressed in code generation:
1. Not all projects are pde related, examples: locus and target platforms;
2. Target platforms  repo master branch has nothing, but all work for mars is in 4.50.x branch, so template generation works but projects in resulting workspace is empty;
3. jbosstools.setup defines Mars repository list with repos from multiple target platform definition, and we have to figure out ether how to use target-platform to update .setup file or use .setup file to generate .target file to avoid manual synchronization.

**Comment by maxandersen** [comment]
@dgolovin can you comment on the line numbers in the templates - then i'm sure i'm not missing anything.

**Comment by dgolovin** [comment]
You can see current fixes through this compare link https://github.com/maxandersen/jbosstools-oomph/compare/templatized-setup...dgolovin:templatized-setup

**Comment by dgolovin** [comment]
I stuck in maven import yesterday with weird problem, should fix them today. Will try to add .target file generation out of jbosstools.setup targlet.

**Comment by dgolovin** [comment]
What do wee need locus p2 repo for? I am asking because I just got werd exception under linux:

``` java
org.eclipse.oomph.util.IORuntimeException: java.io.FileNotFoundException: /home/eskimo/.eclipse/org.eclipse.oomph.p2/cache/https___repository.jboss.org_nexus_content_unzip_unzip_org_jboss_tools_locus_update.site_1.2.0.Final_update.site-1.2.0.Final.zip-unzip_content.jar (File name too long)
    at org.eclipse.oomph.p2.internal.core.CachingTransport.download(CachingTransport.java:199)
    at org.eclipse.oomph.p2.internal.core.CachingTransport.download(CachingTransport.java:219)
    at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:402)
    at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:259)
    at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
    at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
    at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
    at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:344)
    at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:146)
    at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:394)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
    at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
    at org.eclipse.equinox.p2.ui.ProvisioningUI.loadMetadataRepository(ProvisioningUI.java:440)
    at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.getMetadataRepository(MetadataRepositoryElement.java:126)
    at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.fetchChildren(MetadataRepositoryElement.java:75)
    at org.eclipse.equinox.internal.p2.ui.model.RemoteQueriedElement.fetchDeferredChildren(RemoteQueriedElement.java:34)
    at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:232)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: /home/eskimo/.eclipse/org.eclipse.oomph.p2/cache/https___repository.jboss.org_nexus_content_unzip_unzip_org_jboss_tools_locus_update.site_1.2.0.Final_update.site-1.2.0.Final.zip-unzip_content.jar (File name too long)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at org.eclipse.oomph.p2.internal.core.CachingTransport$StatefulFileOutputStream.<init>(CachingTransport.java:452)
    at org.eclipse.oomph.p2.internal.core.CachingTransport.download(CachingTransport.java:176)
    ... 22 more
```

**Comment by dgolovin** [comment]
Because file name length max is 255 and this is obviously oomph cache issue, cache file name generation should take this into consideration.

**Pull request closed without merging**
